import * as fs from 'fs';
import * as path from 'path';
import { effectivePrefs, getConfig, Prefs } from './config';
import { patchKeyValue, patchYamlValue } from './config-patch';
import { Core, downloadServerJar, fetchLatestBuild } from './paper';
import { addInstance, InstanceMeta, listInstances } from './registry';
import { ensureDir, exists, isEmptyDir, writeJson } from './util/fsx';
import { info } from './util/log';

/**
 * 实例模型（DESIGN.md §3）：自包含目录 + 元数据 + 派生配置。
 * 派生文件（server.properties / eula.txt）可由 mcsdev rebuild 幂等重生成，
 * 永不触碰 world/ 与 plugins/。
 */

const EULA = `#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
#本文件由 mcsdev 自动生成；仅用于本地开发测试，请阅读并遵守 Minecraft EULA。
eula=true
`;

/**
 * bukkit.yml 最小种子（首次启动前预写，让"禁用末地"从第一次启动就生效）。
 * 其余键 Paper 启动时会自动补齐（版本自适配），我们绝不整文件覆盖。
 * settings.allow-end 是 Bukkit 自 1.x 起稳定存在的键：false = 不生成/不加载末地。
 */
function bukkitSeed(prefs: Prefs): string {
  return `# bukkit.yml — mcsdev 播种的最小配置；其余设置由服务器首次启动自动补齐（版本自适配）
# 本行勿删：mcsdev rebuild 会按键级合并（保留服务器自己写入的其它配置）
settings:
  allow-end: ${prefs.allowEnd}
`;
}

/** 生成 dev 友好的 server.properties（DESIGN.md §5.2 默认值） */
export function buildServerProperties(prefs: Prefs, port: number): string {
  const nether = prefs.allowNether ? 'true' : 'false';
  // 虚空：level-type 用 flat + 空层 & the_void 生物群系（经典的"空世界"配方）
  const levelType = prefs.worldType === 'normal' ? 'minecraft:normal' : 'minecraft:flat';
  const lines = [
    '#Minecraft server properties — generated by mcsdev (mcsdev rebuild 可重生成)',
    'enable-jmx-monitoring=false',
    'enable-command-block=true',
    'gamemode=survival',
    'force-gamemode=false',
    'difficulty=hard',
    'level-seed=',
    'level-name=world',
    'level-type=' + levelType,
    'generate-structures=true',
    ...(prefs.worldType === 'void'
      ? ['generator-settings={"layers":[],"biome":"minecraft:the_void","structures":{"structures":{}}}']
      : []),
    'allow-nether=' + nether,
    'spawn-protection=0',
    'online-mode=' + prefs.onlineMode,
    'enforce-secure-profile=' + (!prefs.onlineMode),
    'server-port=' + port,
    'motd=' + prefs.motd,
    'max-players=2',
    'view-distance=' + prefs.viewDistance,
    'simulation-distance=' + prefs.viewDistance,
    'white-list=false',
    'enable-rcon=false',
    'enable-query=false',
    'query.port=' + port,
    'pvp=true',
    'max-tick-time=60000',
    'network-compression-threshold=256',
    'use-native-transport=true',
    'sync-chunk-writes=true',
    'entity-broadcast-range-percentage=100',
    'player-idle-timeout=0',
    'rate-limit=0',
    'hardcore=false',
    'broadcast-console-to-ops=true',
    'op-permission-level=4',
    'function-permission-level=2',
    'log-ips=true',
    'spawn-npcs=true',
    'spawn-animals=true',
    'spawn-monsters=true',
    'enforce-whitelist=false',
    'max-world-size=29999984',
    'prevent-proxy-connections=false',
    'hide-online-players=false',
    'require-resource-pack=false',
  ];
  if (!prefs.allowEnd) {
    lines.push('# [mcsdev] allowEnd=false：原版 server.properties 无法禁用末地，真正生效靠 bukkit.yml 的 settings.allow-end=false');
  }
  return lines.join('\n') + '\n';
}

/** 二次替换：在服务器原生 server.properties 上做键级合并（保留版本特有键，只改我们管的键） */
export function mergeServerProperties(prefs: Prefs, port: number, existing: string): string {
  let text = existing;
  const levelType = prefs.worldType === 'normal' ? 'minecraft:normal' : 'minecraft:flat';
  const set = (k: string, v: string): void => {
    text = patchKeyValue(text, k, v);
  };
  set('enable-command-block', 'true');
  set('gamemode', 'survival');
  set('difficulty', 'hard');
  set('level-type', levelType);
  if (prefs.worldType === 'void') {
    set('generator-settings', '{"layers":[],"biome":"minecraft:the_void","structures":{"structures":{}}}');
  }
  set('allow-nether', prefs.allowNether ? 'true' : 'false');
  set('spawn-protection', '0');
  set('online-mode', prefs.onlineMode ? 'true' : 'false');
  set('enforce-secure-profile', String(!prefs.onlineMode));
  set('server-port', String(port));
  set('motd', prefs.motd);
  set('max-players', '2');
  set('view-distance', String(prefs.viewDistance));
  set('simulation-distance', String(prefs.viewDistance));
  return text;
}

/** 写入/合并实例配置（二次替换）：server.properties 与 bukkit.yml 均按键级补丁，不删服务器原生键 */
export function writeInstanceConfigs(prefs: Prefs, port: number, dir: string): void {
  const propsFile = path.join(dir, 'server.properties');
  const existingProps = exists(propsFile) ? fs.readFileSync(propsFile, 'utf8') : null;
  fs.writeFileSync(
    propsFile,
    existingProps === null ? buildServerProperties(prefs, port) : mergeServerProperties(prefs, port, existingProps),
    'utf8'
  );

  const bukkitFile = path.join(dir, 'bukkit.yml');
  const existingBukkit = exists(bukkitFile) ? fs.readFileSync(bukkitFile, 'utf8') : null;
  fs.writeFileSync(
    bukkitFile,
    existingBukkit === null
      ? bukkitSeed(prefs)
      : patchYamlValue(existingBukkit, 'allow-end', String(prefs.allowEnd), 'settings'),
    'utf8'
  );
}

/** 端口自动避让：从 port 起找第一个未被其他实例占用的端口 */
function allocatePort(base: number): number {
  const used = new Set(listInstances().map((i) => i.port));
  for (let p = base; p < base + 100; p++) {
    if (!used.has(p)) return p;
  }
  return base + 100;
}

export interface CreateOptions {
  name: string;
  core: Core;
  mcVersion: string;
  root: string;
  javaBin?: string;
  overrides?: Partial<Prefs>;
  onDownloadProgress?: (received: number, total: number) => void;
}

/** 创建实例：下载 server.jar → 生成 eula/server.properties → 写元数据 → 注册 */
export async function createInstance(opts: CreateOptions): Promise<InstanceMeta> {
  const dir = path.join(opts.root, opts.name);
  if (exists(dir) && !isEmptyDir(dir)) {
    throw new Error(`实例目录已存在且非空：${dir}`);
  }
  ensureDir(dir);

  info(`获取 ${opts.core} ${opts.mcVersion} 最新构建…`);
  const build = await fetchLatestBuild(opts.core, opts.mcVersion);
  if (!build) {
    throw new Error(`PaperMC API 未返回 ${opts.core} ${opts.mcVersion} 的构建信息`);
  }
  info(`构建 #${build.build}（${build.jarName}${build.channel ? `，${build.channel}` : ''}）`);
  await downloadServerJar(opts.core, opts.mcVersion, build, path.join(dir, 'server.jar'), {
    onProgress: opts.onDownloadProgress,
  });

  const cfg = getConfig();
  const prefs = effectivePrefs(cfg, opts.overrides);
  const port = allocatePort(prefs.port);

  fs.writeFileSync(path.join(dir, 'eula.txt'), EULA, 'utf8');
  writeInstanceConfigs(prefs, port, dir);

  const meta: InstanceMeta = {
    name: opts.name,
    core: opts.core,
    mcVersion: opts.mcVersion,
    dir,
    javaBin: opts.javaBin,
    port,
    overrides: opts.overrides ?? {},
    createdAt: new Date().toISOString(),
  };
  writeJson(path.join(dir, 'mcsdev.json'), meta);
  addInstance(meta);
  return meta;
}

/** rebuild：二次替换 —— 把实例偏好按键级合并进现有配置（保留服务器/版本自己的键），首次则播种 */
export function rebuildInstance(meta: InstanceMeta): void {
  const cfg = getConfig();
  const prefs = effectivePrefs(cfg, meta.overrides);
  fs.writeFileSync(path.join(meta.dir, 'eula.txt'), EULA, 'utf8');
  writeInstanceConfigs(prefs, meta.port, meta.dir);
}

/** reset：清世界与日志，重生成派生配置（保留 plugins/server.jar） */
export function resetInstance(meta: InstanceMeta): void {
  for (const name of ['world', 'world_nether', 'world_the_end']) {
    fs.rmSync(path.join(meta.dir, name), { recursive: true, force: true });
  }
  fs.rmSync(path.join(meta.dir, 'logs'), { recursive: true, force: true });
  rebuildInstance(meta);
}