import * as fs from 'fs';
import * as path from 'path';
import { effectivePrefs, getConfig, Prefs } from './config';
import { Core, downloadJar, downloadUrl, fetchLatestBuild } from './paper';
import { addInstance, InstanceMeta, listInstances } from './registry';
import { ensureDir, exists, isEmptyDir, writeJson } from './util/fsx';
import { info } from './util/log';

/**
 * 实例模型（DESIGN.md §3）：自包含目录 + 元数据 + 派生配置。
 * 派生文件（server.properties / eula.txt）可由 mcsdev rebuild 幂等重生成，
 * 永不触碰 world/ 与 plugins/。
 */

const EULA = `#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
#本文件由 mcsdev 自动生成；仅用于本地开发测试，请阅读并遵守 Minecraft EULA。
eula=true
`;

/** 生成 dev 友好的 server.properties（DESIGN.md §5.2 默认值） */
export function buildServerProperties(prefs: Prefs, port: number): string {
  const nether = prefs.allowNether ? 'true' : 'false';
  const levelType = prefs.worldType === 'flat' ? 'minecraft:flat' : 'minecraft:normal';
  const lines = [
    '#Minecraft server properties — generated by mcsdev (mcsdev rebuild 可重生成)',
    'enable-jmx-monitoring=false',
    'enable-command-block=true',
    'gamemode=survival',
    'force-gamemode=false',
    'difficulty=hard',
    'level-seed=',
    'level-name=world',
    'level-type=' + levelType,
    'generate-structures=true',
    'allow-nether=' + nether,
    'spawn-protection=0',
    'online-mode=' + prefs.onlineMode,
    'enforce-secure-profile=' + (!prefs.onlineMode),
    'server-port=' + port,
    'motd=' + prefs.motd,
    'max-players=2',
    'view-distance=' + prefs.viewDistance,
    'simulation-distance=' + prefs.viewDistance,
    'white-list=false',
    'enable-rcon=false',
    'enable-query=false',
    'query.port=' + port,
    'pvp=true',
    'max-tick-time=60000',
    'network-compression-threshold=256',
    'use-native-transport=true',
    'sync-chunk-writes=true',
    'entity-broadcast-range-percentage=100',
    'player-idle-timeout=0',
    'rate-limit=0',
    'hardcore=false',
    'broadcast-console-to-ops=true',
    'op-permission-level=4',
    'function-permission-level=2',
    'log-ips=true',
    'spawn-npcs=true',
    'spawn-animals=true',
    'spawn-monsters=true',
    'enforce-whitelist=false',
    'max-world-size=29999984',
    'prevent-proxy-connections=false',
    'hide-online-players=false',
    'require-resource-pack=false',
  ];
  if (!prefs.allowEnd) {
    lines.push('# [mcsdev] allowEnd=false：server.properties 无法禁用末地，请用插件/数据包实现');
  }
  return lines.join('\n') + '\n';
}

/** 端口自动避让：从 port 起找第一个未被其他实例占用的端口 */
function allocatePort(base: number): number {
  const used = new Set(listInstances().map((i) => i.port));
  for (let p = base; p < base + 100; p++) {
    if (!used.has(p)) return p;
  }
  return base + 100;
}

export interface CreateOptions {
  name: string;
  core: Core;
  mcVersion: string;
  root: string;
  javaBin?: string;
  overrides?: Partial<Prefs>;
  onDownloadProgress?: (received: number, total: number) => void;
}

/** 创建实例：下载 server.jar → 生成 eula/server.properties → 写元数据 → 注册 */
export async function createInstance(opts: CreateOptions): Promise<InstanceMeta> {
  const dir = path.join(opts.root, opts.name);
  if (exists(dir) && !isEmptyDir(dir)) {
    throw new Error(`实例目录已存在且非空：${dir}`);
  }
  ensureDir(dir);

  info(`获取 ${opts.core} ${opts.mcVersion} 最新构建…`);
  const build = await fetchLatestBuild(opts.core, opts.mcVersion);
  if (!build) {
    throw new Error(`PaperMC API 未返回 ${opts.core} ${opts.mcVersion} 的构建信息`);
  }
  const url = downloadUrl(opts.core, opts.mcVersion, build.build, build.jarName);
  info(`下载 build #${build.build}（${build.jarName}）…`);
  await downloadJar(url, path.join(dir, 'server.jar'), {
    sha256: build.sha256,
    onProgress: opts.onDownloadProgress,
  });

  const cfg = getConfig();
  const prefs = effectivePrefs(cfg, opts.overrides);
  const port = allocatePort(prefs.port);

  fs.writeFileSync(path.join(dir, 'eula.txt'), EULA, 'utf8');
  fs.writeFileSync(path.join(dir, 'server.properties'), buildServerProperties(prefs, port), 'utf8');

  const meta: InstanceMeta = {
    name: opts.name,
    core: opts.core,
    mcVersion: opts.mcVersion,
    dir,
    javaBin: opts.javaBin,
    port,
    overrides: opts.overrides ?? {},
    createdAt: new Date().toISOString(),
  };
  writeJson(path.join(dir, 'mcsdev.json'), meta);
  addInstance(meta);
  return meta;
}

/** rebuild：从实例配置幂等重生成派生文件 */
export function rebuildInstance(meta: InstanceMeta): void {
  const cfg = getConfig();
  const prefs = effectivePrefs(cfg, meta.overrides);
  fs.writeFileSync(path.join(meta.dir, 'server.properties'), buildServerProperties(prefs, meta.port), 'utf8');
  fs.writeFileSync(path.join(meta.dir, 'eula.txt'), EULA, 'utf8');
}

/** reset：清世界与日志，重生成派生配置（保留 plugins/server.jar） */
export function resetInstance(meta: InstanceMeta): void {
  for (const name of ['world', 'world_nether', 'world_the_end']) {
    fs.rmSync(path.join(meta.dir, name), { recursive: true, force: true });
  }
  fs.rmSync(path.join(meta.dir, 'logs'), { recursive: true, force: true });
  rebuildInstance(meta);
}